// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FormInput: typeof import('./src/components/Form/Input.vue')['default']
    FormProgress: typeof import('./src/components/Form/Progress.vue')['default']
    'IHeroiconsSolid:eye': typeof import('~icons/heroicons-solid/eye')['default']
    'IHeroiconsSolid:eyeOff': typeof import('~icons/heroicons-solid/eye-off')['default']
    'IHeroiconsSolid:mail': typeof import('~icons/heroicons-solid/mail')['default']
    'IHeroiconsSolid:phone': typeof import('~icons/heroicons-solid/phone')['default']
  }
}

export { }
